apiVersion: v1
kind: Service
metadata:
  name: orion-external
  labels:
    app: orion
spec:
  selector:
    app: orion
  ports:
  - port: 1026
    targetPort: 1026
    protocol: TCP
    name: http
  type: LoadBalancer