apiVersion: v1
kind: Service
metadata:
  name: quantumleap-external
  labels:
    app: quantumleap
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal # プライベートロードバランサーを指定
spec:
  selector:
    app: quantumleap
  ports:
  - port: 8668
    targetPort: 8668
    protocol: TCP
    name: http
  type: LoadBalancer
